// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8YZclfQazorUzJs7Z9G1vGh0uhoyilJ0',
    appId: '1:426074218955:web:f531b6dfb546ca0833d64e',
    messagingSenderId: '426074218955',
    projectId: 'projectquiz-9109e',
    authDomain: 'projectquiz-9109e.firebaseapp.com',
    storageBucket: 'projectquiz-9109e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASg7dO_tdxq2z644pCuNKZH_knk61Mu9A',
    appId: '1:426074218955:android:5150730136f6e14833d64e',
    messagingSenderId: '426074218955',
    projectId: 'projectquiz-9109e',
    storageBucket: 'projectquiz-9109e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4C7xDby2EPn61NN47DEczruQ_D0AB30w',
    appId: '1:426074218955:ios:3245e11b35e3f32d33d64e',
    messagingSenderId: '426074218955',
    projectId: 'projectquiz-9109e',
    storageBucket: 'projectquiz-9109e.appspot.com',
    iosBundleId: 'com.example.projectQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4C7xDby2EPn61NN47DEczruQ_D0AB30w',
    appId: '1:426074218955:ios:3245e11b35e3f32d33d64e',
    messagingSenderId: '426074218955',
    projectId: 'projectquiz-9109e',
    storageBucket: 'projectquiz-9109e.appspot.com',
    iosBundleId: 'com.example.projectQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8YZclfQazorUzJs7Z9G1vGh0uhoyilJ0',
    appId: '1:426074218955:web:64b65134635168c933d64e',
    messagingSenderId: '426074218955',
    projectId: 'projectquiz-9109e',
    authDomain: 'projectquiz-9109e.firebaseapp.com',
    storageBucket: 'projectquiz-9109e.appspot.com',
  );
}
